export const FONTS = [
  { label: 'Default Font', value: '' },
  { label: 'Source Han Sans', value: 'SourceHanSans' },
  { label: 'Source Han Serif', value: 'SourceHanSerif' },
  { label: 'WenDing PL KaiTi', value: 'WenDingPLKaiTi' },
  { label: 'WenDing PL SongTi', value: 'WenDingPLSongTi' },
  { label: 'Zhuque FangSong', value: 'ZhuqueFangSong' },
  { label: 'LXGW WenKai', value: 'LXGWWenKai' },
  { label: 'Alibaba PuHuiTi', value: 'AlibabaPuHuiTi' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Deyi Hei', value: 'DeYiHei' },
  { label: 'Canger Xiaowanzi', value: 'CangerXiaowanzi' },
  { label: 'Youshe Title Black', value: 'YousheTitleBlack' },
  { label: 'Fengguang Mingrui', value: 'FengguangMingrui' },
  { label: 'Shetu Modern Square', value: 'ShetuModernSquare' },
  { label: 'Zcool Happy', value: 'ZcoolHappy' },
  { label: 'Zizhiqu Ximai', value: 'ZizhiQuXiMai' },
  { label: 'Sucai Jishi Kangkang', value: 'SucaiJishiKangkang' },
  { label: 'Sucai Jishi Cool Square', value: 'SucaiJishiCoolSquare' },
  { label: 'Tuniu Rounded', value: 'TuniuRounded' },
  { label: 'Ruizi Zhenyan', value: 'RuiziZhenyan' },
  { label: 'Source Serif 4', value: 'SourceSerif4' },
  { label: 'JetBrains Mono', value: 'JetBrainsMono' },
  { label: 'Literata', value: 'Literata' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'OpenSans' },
  { label: 'Montserrat', value: 'Montserrat' },
  { label: 'Source Sans Pro', value: 'SourceSansPro' },
  { label: 'Merriweather', value: 'Merriweather' },
]